In [1]:
import pandas as pd
import numpy as np
from time import time
from collections import Counter
pd.set_option('display.max_columns', None)
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [4]:
data_dir = '/home/ec2-user/SCB_DATA/FROM_SCB_TXT/'

In [5]:
ls /home/ec2-user/SCB_DATA/FROM_SCB_TXT/

BATB/  CG_extra/         ECPR/              IFNB/  LRRP/  ref_exchange_rate.csv
BDBR/  daily_x_rate.csv  fixed-data/        IFNS/  PFAC/  RSRV/
CG/    ECIF/             Flowcast-ISIC.csv  LBDS/  PSHP/  TRDS/

In [7]:
LEID_lookup = pd.read_csv(data_dir+'Flowcast-ISIC.csv')
LEID_lookup.head()

,otp_id,le_id,lid_sys_gen_id,lid_le_id,lid_isic_tp_val,lid_isic_cd_val,lid_isic_start_dt,create_dt,last_upd_dt,verify_dt,upd_sts_ind,chg_ind,s_startdt,s_starttime,ods
0,100000002,11204367,30372417.0,11204367.0,ISIC,8342.0,2007-06-13T00:00:00.000+08:00,2007-06-18T00:00:00.000+08:00,2013-12-26T00:00:00.000+08:00,2013-12-26T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
1,100000003,11370540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100000005,11590413,31052455.0,11590413.0,ISIC,3815.0,2015-07-31T00:00:00.000+08:00,2011-06-30T00:00:00.000+08:00,2015-09-02T00:00:00.000+08:00,2015-09-02T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
3,100000007,13685565,33417592.0,13685565.0,ISIC,6124.0,2017-05-29T00:00:00.000+08:00,2017-05-30T00:00:00.000+08:00,2017-11-28T00:00:00.000+08:00,2017-11-28T00:00:00.000+08:00,U,N,2017_11_28,2017-11-29 16:47:38,2018_01_30
4,100000008,11537255,30975057.0,11537255.0,ISIC,6125.0,2016-03-02T00:00:00.000+08:00,2011-06-03T00:00:00.000+08:00,2017-08-15T00:00:00.000+08:00,2017-08-15T00:00:00.000+08:00,U,N,2017_08_15,2017-08-16 15:06:50,2018_01_30

In [15]:
data = LEID_lookup[LEID_lookup.columns[:2]].drop_duplicates().dropna()

In [16]:
len(LEID_lookup), len(data)

(11903, 11903)

In [17]:
len(pd.unique(LEID_lookup.otp_id)),len(pd.unique(LEID_lookup.le_id))

(11903, 11666)

In [19]:
data.groupby("le_id").filter(lambda x: len(x) > 1)

          otp_id     le_id
23     100000053  11208628
30     100000077  11148030
32     100000080  11208474
34     100000090  11085485
69     100001023  11156850
79     100001296  11002200
90     100001788  11040275
91     100001812  11018477
132    100002968  11090618
186    100004388  11002187
189    100004445  11001834
231    100004614  11002254
239    100004632  11011559
309    100004758  11044211
329    100004798  11004388
460    100005089  11062853
520    100005205  11168035
564    100005291  11184502
620    100005426  11252216
631    100005452  11002254
760    100006086  11002962
769    100006177  11002585
786    100006309  11002688
788    100006321  11002200
808    100006511  11062085
812    100006525  11010908
814    100006533  11002200
818    100006549  11040704
824    100006579  11012215
825    100006581  11001147
...          ...       ...
10480  100347425  13532110
10496  100348339  11091903
10705  100359841  11225654
10776  100369785  13385057
10809  100377789  13532110
10846  100381927  11060987
10922  100388861  11085485
10925  100389069  11085744
11030  100397124  11062930
11033  100397340  12269926
11043  100397765  11204671
11044  100397766  11204671
11045  100397767  11204671
11046  100397768  11204671
11097  100400530  11157008
11098  100400531  11025984
11219  100409047  11067287
11311  100413075  11084620
11604  600000379  11064119
11608  600000386  11064119
11652  600000602  11118248
11692  600000858  11045441
11693  600000869  11018477
11703  600000946  11044595
11712  600001048  11062583
11720  600001069  11044133
11732  600001123  11045862
11785  600001377  11045012
11851  600001909  11045012
11902  600004114  11084620

[380 rows x 2 columns]

In [22]:
data.sort_values(['le_id'], ascending=True).groupby("le_id").filter(lambda x: len(x) > 1)

          otp_id     le_id
4187   100118350  11000251
8308   100271375  11000251
5926   100228135  11001147
825    100006581  11001147
189    100004445  11001834
1267   100012034  11001834
826    100006583  11002187
186    100004388  11002187
8560   100277107  11002200
79     100001296  11002200
5358   100220404  11002200
788    100006321  11002200
814    100006533  11002200
231    100004614  11002254
631    100005452  11002254
1046   100009511  11002526
8505   100275941  11002526
7605   100255651  11002585
7609   100255694  11002585
769    100006177  11002585
7610   100255695  11002585
786    100006309  11002688
1280   100012730  11002688
1057   100009604  11002962
760    100006086  11002962
10133  100319443  11004388
329    100004798  11004388
812    100006525  11010908
7151   100247336  11010908
4161   100118008  11011559
...          ...       ...
2068   100023634  11626580
9031   100287240  11626580
8592   100277882  11766228
9956   100312324  11766228
10381  100340989  11944563
8869   100284098  11944563
9900   100310883  12007943
5459   100221967  12007943
11033  100397340  12269926
8640   100278954  12269926
8914   100284988  12311245
8584   100277674  12311245
5517   100222802  12641144
9193   100291453  12641144
9523   100300590  12863589
9060   100288422  12863589
9643   100303485  13079651
9253   100292827  13079651
9524   100300616  13289155
9580   100301698  13289155
10776  100369785  13385057
9995   100313564  13385057
10191  100323480  13443208
9993   100313538  13443208
9969   100312776  13448497
10324  100335029  13448497
9627   100303075  13517231
9626   100303074  13517231
10809  100377789  13532110
10480  100347425  13532110

[380 rows x 2 columns]

In [23]:
LEID_lookup.sort_values(['le_id'], ascending=True).groupby("le_id").filter(lambda x: len(x) > 1)

,otp_id,le_id,lid_sys_gen_id,lid_le_id,lid_isic_tp_val,lid_isic_cd_val,lid_isic_start_dt,create_dt,last_upd_dt,verify_dt,upd_sts_ind,chg_ind,s_startdt,s_starttime,ods
4187,100118350,11000251,30001955.0,11000251.0,ISIC,3729.0,2017-08-09T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-07T00:00:00.000+08:00,2017-11-07T00:00:00.000+08:00,U,N,2017_11_07,2017-11-09 02:30:21,2018_01_30
8308,100271375,11000251,30001955.0,11000251.0,ISIC,3729.0,2017-08-09T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-07T00:00:00.000+08:00,2017-11-07T00:00:00.000+08:00,U,N,2017_11_07,2017-11-09 02:30:21,2018_01_30
5926,100228135,11001147,30001262.0,11001147.0,ISIC,8350.0,2015-04-13T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,U,N,2017_12_22,2017-12-23 17:22:47,2018_01_30
825,100006581,11001147,30001262.0,11001147.0,ISIC,8350.0,2015-04-13T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,U,N,2017_12_22,2017-12-23 17:22:47,2018_01_30
189,100004445,11001834,30480149.0,11001834.0,ISIC,3561.0,2013-05-29T00:00:00.000+08:00,2009-05-27T00:00:00.000+08:00,2017-06-19T00:00:00.000+08:00,2017-06-20T00:00:00.000+08:00,U,N,2017_06_20,2017-06-21 16:17:49,2018_01_30
1267,100012034,11001834,30480149.0,11001834.0,ISIC,3561.0,2013-05-29T00:00:00.000+08:00,2009-05-27T00:00:00.000+08:00,2017-06-19T00:00:00.000+08:00,2017-06-20T00:00:00.000+08:00,U,N,2017_06_20,2017-06-21 16:17:49,2018_01_30
826,100006583,11002187,30457256.0,11002187.0,ISIC,3540.0,2017-03-07T00:00:00.000+08:00,2008-11-25T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,U,N,2017_12_27,2017-12-28 16:25:07,2018_01_30
186,100004388,11002187,30457256.0,11002187.0,ISIC,3540.0,2017-03-07T00:00:00.000+08:00,2008-11-25T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,U,N,2017_12_27,2017-12-28 16:25:07,2018_01_30
8560,100277107,11002200,30001539.0,11002200.0,ISIC,3530.0,2012-10-15T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,U,N,2017_11_08,2017-11-09 18:34:49,2018_01_30
79,100001296,11002200,30001539.0,11002200.0,ISIC,3530.0,2012-10-15T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,U,N,2017_11_08,2017-11-09 18:34:49,2018_01_30
5358,100220404,11002200,30001539.0,11002200.0,ISIC,3530.0,2012-10-15T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,U,N,2017_11_08,2017-11-09 18:34:49,2018_01_30
788,100006321,11002200,30001539.0,11002200.0,ISIC,3530.0,2012-10-15T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,U,N,2017_11_08,2017-11-09 18:34:49,2018_01_30
814,100006533,11002200,30001539.0,11002200.0,ISIC,3530.0,2012-10-15T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,2017-11-08T00:00:00.000+08:00,U,N,2017_11_08,2017-11-09 18:34:49,2018_01_30
231,100004614,11002254,30513313.0,11002254.0,ISIC,6131.0,2010-02-25T00:00:00.000+08:00,2009-09-18T00:00:00.000+08:00,2016-12-30T00:00:00.000+08:00,2016-12-30T00:00:00.000+08:00,U,N,2016_12_30,2016-12-31 14:30:52,2018_01_30
631,100005452,11002254,30513313.0,11002254.0,ISIC,6131.0,2010-02-25T00:00:00.000+08:00,2009-09-18T00:00:00.000+08:00,2016-12-30T00:00:00.000+08:00,2016-12-30T00:00:00.000+08:00,U,N,2016_12_30,2016-12-31 14:30:52,2018_01_30
1046,100009511,11002526,30002336.0,11002526.0,ISIC,6124.0,2009-05-27T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-03-22T00:00:00.000+08:00,2017-03-22T00:00:00.000+08:00,U,N,2017_03_22,2017-03-23 15:34:59,2018_01_30
8505,100275941,11002526,30002336.0,11002526.0,ISIC,6124.0,2009-05-27T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-03-22T00:00:00.000+08:00,2017-03-22T00:00:00.000+08:00,U,N,2017_03_22,2017-03-23 15:34:59,2018_01_30
7605,100255651,11002585,30380312.0,11002585.0,ISIC,3831.0,2010-07-30T00:00:00.000+08:00,2007-08-01T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
7609,100255694,11002585,30380312.0,11002585.0,ISIC,3831.0,2010-07-30T00:00:00.000+08:00,2007-08-01T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
769,100006177,11002585,30380312.0,11002585.0,ISIC,3831.0,2010-07-30T00:00:00.000+08:00,2007-08-01T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
7610,100255695,11002585,30380312.0,11002585.0,ISIC,3831.0,2010-07-30T00:00:00.000+08:00,2007-08-01T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,2015-11-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
786,100006309,11002688,30000921.0,11002688.0,ISIC,3849.0,2001-12-18T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2016-07-13T00:00:00.000+08:00,2016-07-13T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
1280,100012730,11002688,30000921.0,11002688.0,ISIC,3849.0,2001-12-18T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2016-07-13T00:00:00.000+08:00,2016-07-13T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
1057,100009604,11002962,30003676.0,11002962.0,ISIC,3121.0,2012-11-12T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,2017-12-28T00:00:00.000+08:00,U,N,2017_12_28,2017-12-29 18:33:06,2018_01_30
760,100006086,11002962,30003676.0,11002962.0,ISIC,3121.0,2012-11-12T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-12-27T00:00:00.000+08:00,2017-12-28T00:00:00.000+08:00,U,N,2017_12_28,2017-12-29 18:33:06,2018_01_30
10133,100319443,11004388,30002876.0,11004388.0,ISIC,6124.0,2016-04-29T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-03-15T00:00:00.000+08:00,2017-03-15T00:00:00.000+08:00,U,N,2017_03_15,2017-03-16 15:51:21,2018_01_30
329,100004798,11004388,30002876.0,11004388.0,ISIC,6124.0,2016-04-29T00:00:00.000+08:00,2001-01-01T00:00:00.000+08:00,2017-03-15T00:00:00.000+08:00,2017-03-15T00:00:00.000+08:00,U,N,2017_03_15,2017-03-16 15:51:21,2018_01_30
812,100006525,11010908,30521057.0,11010908.0,ISIC,6124.0,2009-09-29T00:00:00.000+08:00,2009-10-12T00:00:00.000+08:00,2017-08-24T00:00:00.000+08:00,2017-08-24T00:00:00.000+08:00,U,N,2017_08_24,2017-08-25 18:01:25,2018_01_30
7151,100247336,11010908,30521057.0,11010908.0,ISIC,6124.0,2009-09-29T00:00:00.000+08:00,2009-10-12T00:00:00.000+08:00,2017-08-24T00:00:00.000+08:00,2017-08-24T00:00:00.000+08:00,U,N,2017_08_24,2017-08-25 18:01:25,2018_01_30
4161,100118008,11011559,30276634.0,11011559.0,ISIC,3851.0,2005-02-14T00:00:00.000+08:00,2005-02-15T00:00:00.000+08:00,2016-04-25T00:00:00.000+08:00,2016-04-25T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2068,100023634,11626580,31112147.0,11626580.0,ISIC,6119.0,2015-06-18T00:00:00.000+08:00,2011-07-20T00:00:00.000+08:00,2016-11-15T00:00:00.000+08:00,2016-11-16T00:00:00.000+08:00,U,N,2016_11_16,2016-11-17 14:21:00,2018_01_30
9031,100287240,11626580,31112147.0,11626580.0,ISIC,6119.0,2015-06-18T00:00:00.000+08:00,2011-07-20T00:00:00.000+08:00,2016-11-15T00:00:00.000+08:00,2016-11-16T00:00:00.000+08:00,U,N,2016_11_16,2016-11-17 14:21:00,2018_01_30
8592,100277882,11766228,31302963.0,11766228.0,ISIC,3116.0,2017-03-30T00:00:00.000+08:00,2011-09-30T00:00:00.000+08:00,2017-03-30T00:00:00.000+08:00,2017-03-30T00:00:00.000+08:00,U,N,2017_03_30,2017-03-31 14:52:08,2018_01_30
9956,100312324,11766228,31302963.0,11766228.0,ISIC,3116.0,2017-03-30T00:00:00.000+08:00,2011-09-30T00:00:00.000+08:00,2017-03-30T00:00:00.000+08:00,2017-03-30T00:00:00.000+08:00,U,N,2017_03_30,2017-03-31 14:52:08,2018_01_30
10381,100340989,11944563,31583993.0,11944563.0,ISIC,3513.0,2012-12-11T00:00:00.000+08:00,2011-12-20T00:00:00.000+08:00,2016-07-04T00:00:00.000+08:00,2016-07-04T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
8869,100284098,11944563,31583993.0,11944563.0,ISIC,3513.0,2012-12-11T00:00:00.000+08:00,2011-12-20T00:00:00.000+08:00,2016-07-04T00:00:00.000+08:00,2016-07-04T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9900,100310883,12007943,31650153.0,12007943.0,ISIC,2200.0,2012-02-02T00:00:00.000+08:00,2012-02-02T00:00:00.000+08:00,2017-12-13T00:00:00.000+08:00,2017-12-14T00:00:00.000+08:00,U,N,2017_12_14,2017-12-15 19:15:29,2018_01_30
5459,100221967,12007943,31650153.0,12007943.0,ISIC,2200.0,2012-02-02T00:00:00.000+08:00,2012-02-02T00:00:00.000+08:00,2017-12-13T00:00:00.000+08:00,2017-12-14T00:00:00.000+08:00,U,N,2017_12_14,2017-12-15 19:15:29,2018_01_30
11033,100397340,12269926,31961978.0,12269926.0,ISIC,6124.0,2015-06-30T00:00:00.000+08:00,2012-05-23T00:00:00.000+08:00,2018-01-12T00:00:00.000+08:00,2018-01-12T00:00:00.000+08:00,U,N,2018_01_12,2018-01-13 15:31:47,2018_01_30
8640,100278954,12269926,31961978.0,12269926.0,ISIC,6124.0,2015-06-30T00:00:00.000+08:00,2012-05-23T00:00:00.000+08:00,2018-01-12T00:00:00.000+08:00,2018-01-12T00:00:00.000+08:00,U,N,2018_01_12,2018-01-13 15:31:47,2018_01_30
8914,100284988,12311245,32016856.0,12311245.0,ISIC,6119.0,2015-05-21T00:00:00.000+08:00,2012-06-04T00:00:00.000+08:00,2017-10-26T00:00:00.000+08:00,2017-10-26T00:00:00.000+08:00,U,N,2017_10_26,2017-10-27 16:01:51,2018_01_30
8584,100277674,12311245,32016856.0,12311245.0,ISIC,6119.0,2015-05-21T00:00:00.000+08:00,2012-06-04T00:00:00.000+08:00,2017-10-26T00:00:00.000+08:00,2017-10-26T00:00:00.000+08:00,U,N,2017_10_26,2017-10-27 16:01:51,2018_01_30
5517,100222802,12641144,32420434.0,12641144.0,ISIC,6125.0,2012-09-29T00:00:00.000+08:00,2012-10-08T00:00:00.000+08:00,2014-05-27T00:00:00.000+08:00,2014-05-27T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9193,100291453,12641144,32420434.0,12641144.0,ISIC,6125.0,2012-09-29T00:00:00.000+08:00,2012-10-08T00:00:00.000+08:00,2014-05-27T00:00:00.000+08:00,2014-05-27T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9523,100300590,12863589,32676386.0,12863589.0,ISIC,8342.0,2013-01-31T00:00:00.000+08:00,2013-02-04T00:00:00.000+08:00,2015-02-27T00:00:00.000+08:00,2015-02-27T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9060,100288422,12863589,32676386.0,12863589.0,ISIC,8342.0,2013-01-31T00:00:00.000+08:00,2013-02-04T00:00:00.000+08:00,2015-02-27T00:00:00.000+08:00,2015-02-27T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9643,100303485,13079651,32892490.0,13079651.0,ISIC,3721.0,2016-08-31T00:00:00.000+08:00,2013-05-10T00:00:00.000+08:00,2017-12-15T00:00:00.000+08:00,2017-12-15T00:00:00.000+08:00,U,N,2017_12_15,2017-12-16 22:32:03,2018_01_30
9253,100292827,13079651,32892490.0,13079651.0,ISIC,3721.0,2016-08-31T00:00:00.000+08:00,2013-05-10T00:00:00.000+08:00,2017-12-15T00:00:00.000+08:00,2017-12-15T00:00:00.000+08:00,U,N,2017_12_15,2017-12-16 22:32:03,2018_01_30
9524,100300616,13289155,33094625.0,13289155.0,ISIC,6124.0,2013-08-29T00:00:00.000+08:00,2013-08-29T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,U,N,2017_12_22,2017-12-23 17:22:47,2018_01_30
9580,100301698,13289155,33094625.0,13289155.0,ISIC,6124.0,2013-08-29T00:00:00.000+08:00,2013-08-29T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,2017-12-22T00:00:00.000+08:00,U,N,2017_12_22,2017-12-23 17:22:47,2018_01_30
10776,100369785,13385057,33186732.0,13385057.0,ISIC,3903.0,2014-02-07T00:00:00.000+08:00,2014-02-07T00:00:00.000+08:00,2016-03-22T00:00:00.000+08:00,2016-03-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9995,100313564,13385057,33186732.0,13385057.0,ISIC,3903.0,2014-02-07T00:00:00.000+08:00,2014-02-07T00:00:00.000+08:00,2016-03-22T00:00:00.000+08:00,2016-03-22T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
10191,100323480,13443208,33244214.0,13443208.0,ISIC,8181.0,2014-05-07T00:00:00.000+08:00,2014-05-09T00:00:00.000+08:00,2017-06-09T00:00:00.000+08:00,2017-06-09T00:00:00.000+08:00,U,N,2017_06_09,2017-06-10 22:51:46,2018_01_30
9993,100313538,13443208,33244214.0,13443208.0,ISIC,8181.0,2014-05-07T00:00:00.000+08:00,2014-05-09T00:00:00.000+08:00,2017-06-09T00:00:00.000+08:00,2017-06-09T00:00:00.000+08:00,U,N,2017_06_09,2017-06-10 22:51:46,2018_01_30
9969,100312776,13448497,33249417.0,13448497.0,ISIC,6199.0,2015-01-26T00:00:00.000+08:00,2014-06-10T00:00:00.000+08:00,2015-02-09T00:00:00.000+08:00,2015-02-23T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
10324,100335029,13448497,33249417.0,13448497.0,ISIC,6199.0,2015-01-26T00:00:00.000+08:00,2014-06-10T00:00:00.000+08:00,2015-02-09T00:00:00.000+08:00,2015-02-23T00:00:00.000+08:00,U,N,2016_09_10,2016-09-13 21:03:19,2018_01_30
9627,100303075,13517231,33299378.0,13517231.0,ISIC,3522.0,2015-01-27T00:00:00.000+08:00,2015-02-09T00:00:00.000+08:00,2017-09-20T00:00:00.000+08:00,2017-09-20T00:00:00.000+08:00,U,N,2017_09_20,2017-09-21 18:03:37,2018_01_30
9626,100303074,13517231,33299378.0,13517231.0,ISIC,3522.0,2015-01-27T00:00:00.000+08:00,2015-02-09T00:00:00.000+08:00,2017-09-20T00:00:00.000+08:00,2017-09-20T00:00:00.000+08:00,U,N,2017_09_20,2017-09-21 18:03:37,2018_01_30
10809,100377789,13532110,33305218.0,13532110.0,ISIC,6128.0,2015-03-04T00:00:00.000+08:00,2015-03-04T00:00:00.000+08:00,2016-12-16T00:00:00.000+08:00,2016-12-16T00:00:00.000+08:00,U,N,2016_12_16,2016-12-17 14:13:33,2018_01_30
10480,100347425,13532110,33305218.0,13532110.0,ISIC,6128.0,2015-03-04T00:00:00.000+08:00,2015-03-04T00:00:00.000+08:00,2016-12-16T00:00:00.000+08:00,2016-12-16T00:00:00.000+08:00,U,N,2016_12_16,2016-12-17 14:13:33,2018_01_30

In [ ]:

data.colum
data.to_csv(clien)